#!/usr/bin/env bash
# Configures Nginx server with a 301 redirect

apt-get update
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.html
redirect_config="server {\n\tlisten 80 default_server;\n\tlisten [::]:80 default_server;\n\troot /var/www/html;\n\tindex index.html index.htm index.nginx-debian.html;\n\tserver_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=7U_fFy9vOyY;\n\t}\n\n\tlocation / {\n\t\ttry_files \$uri \$uri/ =404;\n\t}\n}"
echo -e "$redirect_config" > /etc/nginx/sites-available/default
service nginx restart
exit 0
